# Generated by Django 4.0.4 on 2022-04-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_download_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_upload', models.FileField(upload_to='upload_download_files')),
            ],
        ),
    ]
